services:
  lfc-app:
    restart: unless-stopped
    image: ghcr.io/astr0tas/lfc:${TAG:-staging}
    networks:
      - lfc-internal-net

  lfc-nginx:
    image: nginx:alpine
    restart: unless-stopped
    networks:
      - lfc-internal-net

networks:
  lfc-internal-net:
