services:
  app:
    build:
      context: .
      dockerfile: symfony.Dockerfile
    volumes:
      # Mounts the root of your project into the container's workspace
      - ../:/workspace:cached
    command: sleep infinity
    ports:
      - "8000:8000"

  database:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: