services:
  app:
    build:
      context: .
      dockerfile: symfony.Dockerfile
    volumes:
      # 2 way binding the host's source code and the container's
      - ../:/workspace
      # Dedicated volume to store the var and vendor directories inside the container (greatly improve the performance)
      - symfony-var:/workspace/var
      - symfony-vendor:/workspace/vendor
    command: sleep infinity
    ports:
      - "8000:8000"

  database:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
  symfony-var:
  symfony-vendor: